sudo: false

language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/http-kernel:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/yaml:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/monolog-bridge:$SYMFONY_VERSION; fi

install:
  - composer install --prefer-dist
  - composer update --prefer-lowest

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
